// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

import { Translation } from "."

const de: Translation = {
    "nav.title": "Teo Admin Dashboard",
    "nav.collapseButton.tooltip": "Collapse navigation area",
    "nav.expandButton.tooltip": "Expand navigation area",
    "statusBar.langButton.tooltip": "Change the dashboard language",
    "statusBar.lang.language": "Language",
    "statusBar.lang.selectALanguage": "Select a language.",
    "confirm": "Confirm",
}

export default de