// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

import { Translation } from "."

const zhCn: Translation = {
    "nav.title": "张氏管理仪表盘",
    "nav.collapseButton.tooltip": "折叠导航区域",
    "nav.expandButton.tooltip": "展开导航区域",
    "statusBar.langButton.tooltip": "更换仪表盘语言",
    "statusBar.lang.language": "语言",
    "statusBar.lang.selectALanguage": "选择一个语言。",
    "confirm": "确认",
}

export default zhCn