// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

import { Preferences } from "../generated/preferences"

const defaultPreferences: Preferences = {
    lang: "enUs",
    nav: {
        collapsed: false,
        items: [
            { id: "Admin", name: "Admin", icon: "RiAlarmLine", path: "/admin" },
            { id: "User", name: "User", icon: "RiAlarmWarningLine", path: "/user" },
            { id: "Third", name: "Third", icon: "RiAlarmWarningLine", path: "/third" },
            {
                id: "Folder", name: "Folder", icon: "RiAlarmWarningLine", folder: true, childItems: [
                    {
                        id: "Folder item 1", name: "Folder item 1", icon: "RiAlarmLine", path: "/folder-1"
                    },
                    {
                        id: "Folder item 2", name: "Folder item 2", icon: "RiAlarmLine", path: "/folder-2"
                    },
                ]
            }
        ]
    },
    signIn: {
        defaultModel: "Admin",
        user: {
            defaultIdKey: "email",
            defaultCheckerKey: "password"
        },
        admin: {
            defaultIdKey: "email",
            defaultCheckerKey: "password"
        }
    }
}

export default defaultPreferences