// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

import { Preferences } from "../generated/preferences"

const defaultPreferences: Preferences = {
    lang: "enUs",
    nav: {
        collapsed: false,
        items: [
            { id: "Admin", name: "Admin", icon: "RiAlarmLine", path: "Admin" },
            { id: "User", name: "User", icon: "RiAlarmWarningLine", path: "User" },
        ]
    },
    signIn: {
        defaultModel: "Admin",
        user: {
            defaultIdKey: "email",
            defaultCheckerKey: "password"
        },
        admin: {
            defaultIdKey: "email",
            defaultCheckerKey: "password"
        }
    }
}

export default defaultPreferences