// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

export const phonePortraitMax = '575px'

export const phoneLandscapeMin = '576px'

export const phoneLandscapeMax = '767px'

export const tabletMin = '768px'

export const tabletMax = '991px'

export const desktopMin = '992px'

export const desktopMax = '1199px'

export const desktopHDMin = '1200px'

export const appBackgroundColorLight = "#F6F6F8"

export const appBackgroundColorDark = "#090C13"

export const appNavBackgroundColorLight = "#FFFFFF"

export const appNavBackgroundColorDark = "#212A3D"

export const spacing = "8px"

export const margin = "20px"