// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

export const phonePortraitMax = '575px'

export const phoneLandscapeMin = '576px'

export const phoneLandscapeMax = '767px'

export const tabletMin = '768px'

export const tabletMax = '991px'

export const desktopMin = '992px'

export const desktopMax = '1199px'

export const desktopHDMin = '1200px'

export const shallowShadow = `rgba(0, 0, 0, .1) 0 1px 1px`

export const innerShallowShadow = `inset rgba(0, 0, 0, .1) 0px 0px 6px -2px`

export const shallowShadowX = `rgba(0, 0, 0, .1) 1px 0 1px`

export const tintColorLight = "#0052FF"

export const tintColorDark = "#0052FF"

export const tintColorContrastLight = "#0052FF"

export const tintColorContrastDark = "#0052FF"

export const controlTintColorLight = "#015ECC"

export const controlTintColorDark = "#015ECC"

export const controlTintColorContrastLight = "#015ECC"

export const controlTintColorContrastDark = "#015ECC"

export const appBackgroundColorLight = "#FBFBFD"

export const appBackgroundColorDark = "#0a0a0c"

export const appNavBackgroundColorLight = "#FFFFFF"

export const appNavBackgroundColorDark = "#000000"

export const appStatusBarBackgroundColorLight = "#FFFFFF"

export const appStatusBarBackgroundColorDark = "#000000"

export const appContentBackgroundColorLight = "#FFFFFF"

export const appContentBackgroundColorDark = "#000000"

export const controlBackgroundColorLight = "#F6F6F8"

export const controlBackgroundColorDark = "#1a1a1c"

export const controlBorderColorLight = "#EBEBED"

export const controlBorderColorDark = "#141416"

export const controlHintBackgroundColorLight = "#FAFAFC"

export const controlHintBackgroundColorDark = "#1e1e21"

export const controlActiveBackgroundColorLight = "#EFEFF2"

export const controlActiveBackGroundColorDark = "#202022"

export const controlTextColorLight = "#404040"

export const controlTextColorDark = "#bfbfc2"

export const subtitleTextColorLight = "#4A4A4C"

export const subtitleTextColorDark = "#b5b5b7"

export const captionTextColorLight = "#ACACAE"

export const captionTextColorDark = "#535355"

export const spacing = "8px"

export const margin = "16px"

export const controlHeight = `calc(1.25rem + ${margin})`

export const controlHeightDoubled = `calc((1.25rem + ${margin}) * 2)`

export const controlRadius = `calc((1.25rem + ${margin}) / 2)`

export const radius = "4px"

export const paperRadius = "8px"

export const navBarHeight = `calc(3 * ${margin} + 1.25rem)`

export const borderThin = "0.5px"

export const defaultTransitionTimeInterval = '0.2s'

export const shortTransitionTimeInterval = '0.1s'

export const defaultTransitionCurve = 'ease-in-out'

export const textColorOnTintedBackgroundLight = 'white'

export const textColorOnTintedBackgroundDark = 'black'

export const panelBoxShadow = `
rgb(0 0 0 / 50%) 0px 0px 1px, rgb(0 0 0 / 3%) 0px 100px 80px,
rgb(0 0 0 / 2%) 0px 41.7776px 33.4221px,
rgb(0 0 0 / 2%) 0px 22.3363px 17.869px,
rgb(0 0 0 / 4%) 0px 12.5216px 10.0172px`

export const popUpShadow = `
rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
rgba(0, 0, 0, 0) 0px 0px 0px 0px, 
rgba(30, 58, 58, 0.05) 0px 10px 15px -3px, 
rgba(30, 58, 58, 0.05) 0px 4px 6px -4px
`

export const zIndexTooltip = 11
export const zIndexMenu = 10
export const zIndexModal = 3
export const zIndexNav = 2
export const zIndexStatusBar = 1