// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

import { styled } from "@linaria/react"
import { clearHeading, transitionAll } from '../../../lib/generated/theme'
import { spacing } from '../../../lib/extended/theme'

export type NavAppTitleProps = {
    collapsed: boolean
}

const NavAppTitleElement = styled.h1<NavAppTitleProps>`
    ${clearHeading}
    margin-top: ${spacing};
    font-size: ${({ collapsed }) => collapsed ? `0.75rem` : `1rem`};
    text-align: center;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: clip;
    ${transitionAll}
`

export default NavAppTitleElement