// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

import ButtonElement from "../../generated/button/ButtonElement"

const Button = ButtonElement

export default Button