// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

import React from 'react'
import AppRoot from './AppRoot'
import AppNavLayout from './AppNavLayout'
import Nav from '../generated/Nav'
import AppContentLayout from './AppContentLayout'
import StatusBar from './StatusBar'

const App = () => {
    return <AppRoot>
        <AppNavLayout>
            <Nav />
            <AppContentLayout>
                <StatusBar />
            </AppContentLayout>
        </AppNavLayout>
    </AppRoot>
}

export default App