// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

import { styled } from "@linaria/react"
import { radius } from "../../lib/extended/theme"
import { dark, flexContainer, light } from "../../lib/generated/theme"

export type ContextMenuItemElementProps = {
    disabled?: boolean
    highlighted?: boolean
}

const ContextMenuItemElement = styled.div<ContextMenuItemElementProps>`
    padding: ${radius};
    border-radius: ${radius};
    ${flexContainer("row", "center")}
    user-select: none;
    cursor: default;
    ${light} {
        background-color: ${({ highlighted }) => highlighted ? `blue` : `white`};
        color: ${({ disabled }) => disabled ? `gray` : `black`}
    }
    ${dark} {
        background-color: ${({ highlighted }) => highlighted ? `blue` : `black`};
        color: ${({ disabled }) => disabled ? `gray` : `white`}
    }
`

export default ContextMenuItemElement