// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

import { styled } from "@linaria/react"
import { borderThin, radius } from "../../lib/extended/theme"
import { dark, flexContainer, light } from "../../lib/generated/theme"

const MenuElement = styled.div`
    padding: ${radius};
    border-radius: ${radius};
    font-size: 0.875rem;
    ${flexContainer("column", "stretch")}
    ${light} {
        background-color: white;
        border: ${borderThin} solid gray;
    }
    ${dark} {
        background-color: black;
        border: ${borderThin} solid gray;
    }
`

export default MenuElement