// This file is generated by Teo generator for extending purpose.
// The file content will not be overwritten between generations. Be careful to 
// modify this file. Do not modify export names and siganatures. Modify values 
// with care.

import React from 'react'
import { PageStackItem } from "../../generated/pageStack/PageStackItem"
import renderDefaultStackItem from "../../generated/pageStack/renderDefaultStackItem"
import renderNotFound from "../../generated/pageStack/renderNotFound"
import StackItemIndexContext from "../../generated/pageStack/stackItemIndexContext"

export default function renderStackItem(item: PageStackItem, index: number, topMost: boolean) {
    const element = <StackItemIndexContext.Provider value={{ index, topMost }}>
        {renderDefaultStackItem(item)}
    </StackItemIndexContext.Provider>
    
    if (element) {
        return element
    }
    // write your own page items here
    return renderNotFound()
}